#!/bin/bash

cp ../cumulus_dgx_reference/inventories/dgx_2node/topology.svg 2node.svg
sed -i '1,3d' 2node.svg
sed -i 's/font-size:1.00001em/font-size:12px/' 2node.svg
sed -i '/<!-- Unsupported Record/d' 2node.svg
sed -i '/<title>/d' 2node.svg
sed -i 's/group1235-141/oob-mgmt-server/' 2node.svg
sed -i 's/group1223-99/gpu-stg-leaf01/' 2node.svg
sed -i 's/group1224-106/gpu-stg-leaf02/' 2node.svg
sed -i 's/group1231-113/compute01/' 2node.svg
sed -i 's/group1232-120/compute02/' 2node.svg
sed -i 's/group1233-127/storage01/' 2node.svg
sed -i 's/group1234-134/storage02/' 2node.svg
cp ../cumulus_dgx_reference/inventories/dgx_4node/topology.svg 4node.svg
sed -i '1,3d' 4node.svg
sed -i 's/font-size:1.00001em/font-size:12px/' 4node.svg
sed -i '/<!-- Unsupported Record/d' 4node.svg
sed -i '/<title>/d' 4node.svg
sed -i 's/group1316-208/oob-mgmt-server/' 4node.svg
sed -i 's/group1302-124/gpu-spine01/' 4node.svg
sed -i 's/group1303-131/gpu-spine02/' 4node.svg
sed -i 's/group1313-201/gpu-leaf01/' 4node.svg
sed -i 's/group1312-194/gpu-leaf02/' 4node.svg
sed -i 's/group1306-152/stg-leaf01/' 4node.svg
sed -i 's/group1307-159/stg-leaf02/' 4node.svg
sed -i 's/group1311-187/compute01/' 4node.svg
sed -i 's/group1310-180/compute02/' 4node.svg
sed -i 's/group1309-173/compute03/' 4node.svg
sed -i 's/group1308-166/compute04/' 4node.svg
sed -i 's/group1304-138/storage01/' 4node.svg
sed -i 's/group1305-145/storage02/' 4node.svg
cp ../cumulus_dgx_reference/inventories/dgx_8node/topology.svg 8node.svg
sed -i '1,3d' 8node.svg
sed -i 's/font-size:1.00001em/font-size:12px/' 8node.svg
git commit -am 'Updated via update script'; git push