#!/bin/bash

cp ../cumulus_dgx_reference/inventories/dgx_2node/topology/topology.svg 2node.svg
sed -i '1,3d' 2node.svg
sed -i 's/font-size:1.00001em/font-size:12px/' 2node.svg
sed -i '/<!-- Unsupported Record/d' 2node.svg
sed -i '/<title>/d' 2node.svg
sed -i 's/group1235-141/oob-mgmt-server/' 2node.svg
sed -i 's/group1223-99/gpu-stg-leaf01/' 2node.svg
sed -i 's/group1224-106/gpu-stg-leaf02/' 2node.svg
sed -i 's/group1231-113/compute01/' 2node.svg
sed -i 's/group1232-120/compute02/' 2node.svg
sed -i 's/group1233-127/storage01/' 2node.svg
sed -i 's/group1234-134/storage02/' 2node.svg
cp ../cumulus_dgx_reference/inventories/dgx_4node/topology/topology.svg 4node.svg
sed -i '1,3d' 4node.svg
sed -i 's/font-size:1.00001em/font-size:12px/' 4node.svg
sed -i '/<!-- Unsupported Record/d' 4node.svg
sed -i '/<title>/d' 4node.svg
sed -i 's/group1316-208/oob-mgmt-server/' 4node.svg
sed -i 's/group1302-124/gpu-spine01/' 4node.svg
sed -i 's/group1303-131/gpu-spine02/' 4node.svg
sed -i 's/group1313-201/gpu-leaf01/' 4node.svg
sed -i 's/group1312-194/gpu-leaf02/' 4node.svg
sed -i 's/group1306-152/stg-leaf01/' 4node.svg
sed -i 's/group1307-159/stg-leaf02/' 4node.svg
sed -i 's/group1311-187/compute01/' 4node.svg
sed -i 's/group1310-180/compute02/' 4node.svg
sed -i 's/group1309-173/compute03/' 4node.svg
sed -i 's/group1308-166/compute04/' 4node.svg
sed -i 's/group1304-138/storage01/' 4node.svg
sed -i 's/group1305-145/storage02/' 4node.svg
cp ../cumulus_dgx_reference/inventories/dgx_8node/topology/topology.svg 8node.svg
sed -i '1,3d' 8node.svg
sed -i 's/font-size:1.00001em/font-size:12px/' 8node.svg
sed -i '/<!-- Unsupported Record/d' 8node.svg
sed -i '/<title>/d' 8node.svg
sed -i 's/group2044-380/oob-mgmt-server/' 8node.svg
sed -i 's/group2040-352/gpu-spine01/' 8node.svg
sed -i 's/group2041-359/gpu-spine02/' 8node.svg
sed -i 's/group2042-366/gpu-spine03/' 8node.svg
sed -i 's/group2043-373/gpu-spine04/' 8node.svg
sed -i 's/group2060-492/gpu-leaf01/' 8node.svg
sed -i 's/group2059-485/gpu-leaf02/' 8node.svg
sed -i 's/group2058-478/gpu-leaf03/' 8node.svg
sed -i 's/group2057-471/gpu-leaf04/' 8node.svg
sed -i 's/group2047-401/stg-leaf01/' 8node.svg
sed -i 's/group2048-408/stg-leaf02/' 8node.svg
sed -i 's/group2056-464/compute01/' 8node.svg
sed -i 's/group2055-457/compute02/' 8node.svg
sed -i 's/group2054-450/compute03/' 8node.svg
sed -i 's/group2053-443/compute04/' 8node.svg
sed -i 's/group2052-436/compute05/' 8node.svg
sed -i 's/group2051-429/compute06/' 8node.svg
sed -i 's/group2050-422/compute07/' 8node.svg
sed -i 's/group2049-415/compute08/' 8node.svg
sed -i 's/group2045-387/storage01/' 8node.svg
sed -i 's/group2046-394/storage02/' 8node.svg
git commit -am 'Updated via update script'; git push
